---
# Przykładowy playbook zbierający informacje o macierzy IBM FS

- hosts: localhost    # Za wykonanie modułów ibm.storage_virtualize odpowiada stacja kontrolna
  gather_facts: false # bo nie obchodzi mnie co wiem o localhost

  tasks:
    - name: "Uwierzytelnienie na jako {{ fs_user }} na {{ fs_cluster }}"
      register: auth_info   # auth_info.token pozwala potem nie użwać user i hasła
      ibm.storage_virtualize.ibm_svc_auth:
        clustername: "{{ fs_cluster }}"
        log_path: "{{ fs_log }}"
        username: "{{ fs_user }}"
        password: "{{ fs_pass }}"
      tags:
        - always      # Uwierzytelnić zawsze się trzeba
    
    - name: Tworzenie sklonowanego LUNu pod OSa - źródłem jest LUN common_master_os
      ibm.storage_virtualize.ibm_svc_manage_volume:
        clustername: "{{ fs_cluster }}"
        log_path: "{{ fs_log }}"
        token: "{{ auth_info.token }}"
        name: "{{ my_vdisk }}"
        state: "present"
        pool: "{{ fs_pool }}"
      #  size: "{{ my_vdisk_size }}"    # to jest do stawiania LUNu od 0
      #  unit: "gb"
        type: "thinclone"
        fromsourcevolume: "{{ src_vdisk }}"
        iogrp: "io_grp0"
        novolumegroup: True
      tags:
        - "MKVDISK"
      
    - name: Mapowanie LUNu na klaster VIOSów
      ibm.storage_virtualize.ibm_svc_vol_map:
        clustername: "{{ fs_cluster }}"
        log_path: "{{ fs_log }}"
        token: "{{ auth_info.token }}"
        volname: "{{ my_vdisk }}"
        state: "present"
        hostcluster: "{{ vios_cluster }}"
      tags:
        - "VDISKMAP"